/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 interview_desk.gltf --transform 
Files: interview_desk.gltf [133.49MB] > C:\Users\Abiye\Downloads\interview_desk-transformed.glb [5.19MB] (96%)
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';

import officeScene from '../assets/3d/office.glb';

const Office = (props) => {
  const { nodes, materials } = useGLTF('/office.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Seat.geometry} material={materials.PaletteMaterial002} position={[2.002, 1.237, -0.703]} scale={[0.569, 0.048, 0.569]} />
      <mesh geometry={nodes.Laptop.geometry} material={materials['Plastic 01']} position={[0.113, 2.094, 0.154]} rotation={[-Math.PI, 1.184, -Math.PI]} scale={2.724} />
      <mesh geometry={nodes.Water_Bottle.geometry} material={materials['Aluminium sand']} position={[-0.553, 2.371, 0.705]} rotation={[Math.PI, 0, Math.PI]} scale={2.086} />
      <mesh geometry={nodes.Mug.geometry} material={materials.PaletteMaterial004} position={[0.704, 2.138, -1.377]} rotation={[Math.PI, 0, Math.PI]} scale={2.023} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.PaletteMaterial005} position={[0.101, 0.223, 0.162]} scale={0.021} />
      <mesh geometry={nodes.Desk001_Table_black_0.geometry} material={materials.PaletteMaterial001} position={[0.004, 1.187, 0.081]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.812} />
      <mesh geometry={nodes.Knob001.geometry} material={materials.PaletteMaterial003} position={[1.016, 1.65, 1.573]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.812} />
      <mesh geometry={nodes.Keyboard.geometry} material={materials['Material.002']} position={[0.077, 2.102, 0.162]} rotation={[-Math.PI, 1.184, -Math.PI]} scale={2.724} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['couro 2k']} position={[0.236, 2.079, -0.796]} rotation={[-0.036, 0.979, 0.03]} scale={1.98} />
      <mesh geometry={nodes.Plane083.geometry} material={materials.Paper} position={[0.237, 2.085, -0.796]} rotation={[-0.036, 0.979, 0.03]} scale={1.98} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Paper.001']} position={[-0.098, 2.147, 1.21]} rotation={[Math.PI, -1.395, Math.PI]} scale={[2.127, 0.021, 2.127]} />
      <mesh geometry={nodes.Flowers.geometry} material={materials['flower.001']} position={[-0.73, 2.814, 1.925]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.143} />
      <group position={[-0.493, 2.579, 1.879]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.143}>
        <mesh geometry={nodes.twig.geometry} material={materials.leaf_root} />
        <mesh geometry={nodes.twig_1.geometry} material={materials['leaf.002']} />
      </group>
      <instancedMesh args={[nodes.Cube013.geometry, materials.PaletteMaterial002, 8]} instanceMatrix={nodes.Cube013.instanceMatrix} />
      <instancedMesh args={[nodes.Cylinder011.geometry, materials.PaletteMaterial002, 8]} instanceMatrix={nodes.Cylinder011.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/office.glb')

export default Office;